int add(int ,int );  //FUNCTION  PROTOTYPE ,IT TAKE TWO INTEGER INPUT AND RETURN TYPE IS INTEGER ,USE BOTH ARGUMENT AND ADD THEM//
int sub(int ,int );  //FUNCTION  PROTOTYPE ,IT TAKE TWO INTEGER INPUT AND RETURN TYPE IS INTEGER ,USE BOTH ARGUMENT AND SUBSTRACT  THEM//
